// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlcpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditCount = `-- name: AuditCount :one
SELECT COUNT(1)
FROM audit_logs a
LEFT JOIN user_credentials c ON c.user_id::text = a.target_id
WHERE ($1 = '' OR a.module = $1)
  AND ($2 = '' OR a.action = $2)
  AND ($3 = '' OR a.result = $3)
  AND ($4 = '' OR a.operator_user_id::text = $4)
  AND ($5 = '' OR a.target_type = $5)
  AND ($6 = '' OR a.target_id = $6)
  AND ($7 = '' OR a.request_id = $7)
  AND ($8 = '' OR a.operator_tenant_id::text = $8)
  AND ($9 = '' OR a.created_at >= $9::timestamptz)
  AND ($10 = '' OR a.created_at <= $10::timestamptz)
  AND ($11 = '' OR a.target_name ILIKE '%' || $11 || '%' OR a.target_id ILIKE '%' || $11 || '%')
`

type AuditCountParams struct {
	Module         interface{} `json:"module"`
	Action         interface{} `json:"action"`
	Result         interface{} `json:"result"`
	OperatorUserID interface{} `json:"operator_user_id"`
	TargetType     interface{} `json:"target_type"`
	TargetID       interface{} `json:"target_id"`
	RequestID      interface{} `json:"request_id"`
	TenantID       interface{} `json:"tenant_id"`
	DateFrom       interface{} `json:"date_from"`
	DateTo         interface{} `json:"date_to"`
	Keyword        interface{} `json:"keyword"`
}

func (q *Queries) AuditCount(ctx context.Context, arg AuditCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, auditCount,
		arg.Module,
		arg.Action,
		arg.Result,
		arg.OperatorUserID,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.TenantID,
		arg.DateFrom,
		arg.DateTo,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const auditCreate = `-- name: AuditCreate :exec
INSERT INTO audit_logs (
    id, request_id, operator_user_id, operator_role, operator_tenant_id,
    operator_username, operator_display_name,
    target_type, target_id, target_name, action, module, result, error_code,
    before_json, after_json, changed_fields, ip, user_agent, created_at
)
VALUES (
    $1::uuid,
    $2,
    NULLIF($3, '')::uuid,
    NULLIF($4, ''),
    NULLIF($5, '')::uuid,
    COALESCE(NULLIF($6, ''), (SELECT c.account FROM user_credentials c WHERE c.user_id = NULLIF($3, '')::uuid LIMIT 1), ''),
    COALESCE(NULLIF($7, ''), (SELECT u.name FROM users u WHERE u.id = NULLIF($3, '')::uuid LIMIT 1), ''),
    $8,
    NULLIF($9, ''),
    COALESCE(
        NULLIF($10, ''),
        CASE
            WHEN $8 = 'user' THEN (SELECT c.account FROM user_credentials c WHERE c.user_id::text = NULLIF($9, '') LIMIT 1)
            ELSE ''
        END
    ),
    $11,
    $12,
    $13,
    NULLIF($14, ''),
    $15::jsonb,
    $16::jsonb,
    $17::jsonb,
    NULLIF($18, ''),
    NULLIF($19, ''),
    $20
)
`

type AuditCreateParams struct {
	ID                  pgtype.UUID        `json:"id"`
	RequestID           string             `json:"request_id"`
	OperatorUserID      interface{}        `json:"operator_user_id"`
	OperatorRole        interface{}        `json:"operator_role"`
	OperatorTenantID    interface{}        `json:"operator_tenant_id"`
	OperatorUsername    interface{}        `json:"operator_username"`
	OperatorDisplayName interface{}        `json:"operator_display_name"`
	TargetType          string             `json:"target_type"`
	TargetID            interface{}        `json:"target_id"`
	TargetName          interface{}        `json:"target_name"`
	Action              string             `json:"action"`
	Module              string             `json:"module"`
	Result              string             `json:"result"`
	ErrorCode           interface{}        `json:"error_code"`
	BeforeJson          []byte             `json:"before_json"`
	AfterJson           []byte             `json:"after_json"`
	ChangedFields       []byte             `json:"changed_fields"`
	Ip                  interface{}        `json:"ip"`
	UserAgent           interface{}        `json:"user_agent"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AuditCreate(ctx context.Context, arg AuditCreateParams) error {
	_, err := q.db.Exec(ctx, auditCreate,
		arg.ID,
		arg.RequestID,
		arg.OperatorUserID,
		arg.OperatorRole,
		arg.OperatorTenantID,
		arg.OperatorUsername,
		arg.OperatorDisplayName,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.Action,
		arg.Module,
		arg.Result,
		arg.ErrorCode,
		arg.BeforeJson,
		arg.AfterJson,
		arg.ChangedFields,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const auditGetByID = `-- name: AuditGetByID :one
SELECT
    a.id::text AS id,
    a.request_id,
    COALESCE(a.operator_user_id::text, '') AS operator_user_id,
    COALESCE(a.operator_role, '') AS operator_role,
    COALESCE(a.operator_tenant_id::text, '') AS operator_tenant_id,
    COALESCE(a.operator_username, '') AS operator_username,
    COALESCE(a.operator_display_name, '') AS operator_display_name,
    a.target_type,
    COALESCE(a.target_id, '') AS target_id,
    COALESCE(NULLIF(a.target_name, ''), CASE WHEN a.target_type = 'user' THEN COALESCE(c.account, '') ELSE '' END) AS target_name,
    a.action,
    a.module,
    a.result,
    COALESCE(a.error_code, '') AS error_code,
    a.before_json,
    a.after_json,
    a.changed_fields,
    COALESCE(a.ip, '') AS ip,
    COALESCE(a.user_agent, '') AS user_agent,
    a.created_at
FROM audit_logs a
LEFT JOIN user_credentials c ON c.user_id::text = a.target_id
WHERE a.id = $1::uuid
`

type AuditGetByIDRow struct {
	ID                  string             `json:"id"`
	RequestID           string             `json:"request_id"`
	OperatorUserID      interface{}        `json:"operator_user_id"`
	OperatorRole        string             `json:"operator_role"`
	OperatorTenantID    interface{}        `json:"operator_tenant_id"`
	OperatorUsername    string             `json:"operator_username"`
	OperatorDisplayName string             `json:"operator_display_name"`
	TargetType          string             `json:"target_type"`
	TargetID            string             `json:"target_id"`
	TargetName          interface{}        `json:"target_name"`
	Action              string             `json:"action"`
	Module              string             `json:"module"`
	Result              string             `json:"result"`
	ErrorCode           string             `json:"error_code"`
	BeforeJson          []byte             `json:"before_json"`
	AfterJson           []byte             `json:"after_json"`
	ChangedFields       []byte             `json:"changed_fields"`
	Ip                  string             `json:"ip"`
	UserAgent           string             `json:"user_agent"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AuditGetByID(ctx context.Context, id pgtype.UUID) (AuditGetByIDRow, error) {
	row := q.db.QueryRow(ctx, auditGetByID, id)
	var i AuditGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.OperatorUserID,
		&i.OperatorRole,
		&i.OperatorTenantID,
		&i.OperatorUsername,
		&i.OperatorDisplayName,
		&i.TargetType,
		&i.TargetID,
		&i.TargetName,
		&i.Action,
		&i.Module,
		&i.Result,
		&i.ErrorCode,
		&i.BeforeJson,
		&i.AfterJson,
		&i.ChangedFields,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const auditListPage = `-- name: AuditListPage :many
SELECT
    a.id::text AS id,
    a.request_id,
    COALESCE(a.operator_user_id::text, '') AS operator_user_id,
    COALESCE(a.operator_role, '') AS operator_role,
    COALESCE(a.operator_tenant_id::text, '') AS operator_tenant_id,
    COALESCE(a.operator_username, '') AS operator_username,
    COALESCE(a.operator_display_name, '') AS operator_display_name,
    a.target_type,
    COALESCE(a.target_id, '') AS target_id,
    COALESCE(NULLIF(a.target_name, ''), CASE WHEN a.target_type = 'user' THEN COALESCE(c.account, '') ELSE '' END) AS target_name,
    a.action,
    a.module,
    a.result,
    COALESCE(a.error_code, '') AS error_code,
    a.before_json,
    a.after_json,
    a.changed_fields,
    COALESCE(a.ip, '') AS ip,
    COALESCE(a.user_agent, '') AS user_agent,
    a.created_at
FROM audit_logs a
LEFT JOIN user_credentials c ON c.user_id::text = a.target_id
WHERE ($1 = '' OR a.module = $1)
  AND ($2 = '' OR a.action = $2)
  AND ($3 = '' OR a.result = $3)
  AND ($4 = '' OR a.operator_user_id::text = $4)
  AND ($5 = '' OR a.target_type = $5)
  AND ($6 = '' OR a.target_id = $6)
  AND ($7 = '' OR a.request_id = $7)
  AND ($8 = '' OR a.operator_tenant_id::text = $8)
  AND ($9 = '' OR a.created_at >= $9::timestamptz)
  AND ($10 = '' OR a.created_at <= $10::timestamptz)
  AND ($11 = '' OR a.target_name ILIKE '%' || $11 || '%' OR a.target_id ILIKE '%' || $11 || '%')
ORDER BY a.created_at DESC, a.id DESC
LIMIT $13 OFFSET $12
`

type AuditListPageParams struct {
	Module         interface{} `json:"module"`
	Action         interface{} `json:"action"`
	Result         interface{} `json:"result"`
	OperatorUserID interface{} `json:"operator_user_id"`
	TargetType     interface{} `json:"target_type"`
	TargetID       interface{} `json:"target_id"`
	RequestID      interface{} `json:"request_id"`
	TenantID       interface{} `json:"tenant_id"`
	DateFrom       interface{} `json:"date_from"`
	DateTo         interface{} `json:"date_to"`
	Keyword        interface{} `json:"keyword"`
	OffsetRows     int32       `json:"offset_rows"`
	LimitRows      int32       `json:"limit_rows"`
}

type AuditListPageRow struct {
	ID                  string             `json:"id"`
	RequestID           string             `json:"request_id"`
	OperatorUserID      interface{}        `json:"operator_user_id"`
	OperatorRole        string             `json:"operator_role"`
	OperatorTenantID    interface{}        `json:"operator_tenant_id"`
	OperatorUsername    string             `json:"operator_username"`
	OperatorDisplayName string             `json:"operator_display_name"`
	TargetType          string             `json:"target_type"`
	TargetID            string             `json:"target_id"`
	TargetName          interface{}        `json:"target_name"`
	Action              string             `json:"action"`
	Module              string             `json:"module"`
	Result              string             `json:"result"`
	ErrorCode           string             `json:"error_code"`
	BeforeJson          []byte             `json:"before_json"`
	AfterJson           []byte             `json:"after_json"`
	ChangedFields       []byte             `json:"changed_fields"`
	Ip                  string             `json:"ip"`
	UserAgent           string             `json:"user_agent"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AuditListPage(ctx context.Context, arg AuditListPageParams) ([]AuditListPageRow, error) {
	rows, err := q.db.Query(ctx, auditListPage,
		arg.Module,
		arg.Action,
		arg.Result,
		arg.OperatorUserID,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.TenantID,
		arg.DateFrom,
		arg.DateTo,
		arg.Keyword,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditListPageRow
	for rows.Next() {
		var i AuditListPageRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.OperatorUserID,
			&i.OperatorRole,
			&i.OperatorTenantID,
			&i.OperatorUsername,
			&i.OperatorDisplayName,
			&i.TargetType,
			&i.TargetID,
			&i.TargetName,
			&i.Action,
			&i.Module,
			&i.Result,
			&i.ErrorCode,
			&i.BeforeJson,
			&i.AfterJson,
			&i.ChangedFields,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
