// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlcpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authCreateLoginChallenge = `-- name: AuthCreateLoginChallenge :exec
INSERT INTO login_challenges (id, user_id, otp_hash, expires_at, attempts, verified_at, created_at)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type AuthCreateLoginChallengeParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	OtpHash    string             `json:"otp_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AuthCreateLoginChallenge(ctx context.Context, arg AuthCreateLoginChallengeParams) error {
	_, err := q.db.Exec(ctx, authCreateLoginChallenge,
		arg.ID,
		arg.UserID,
		arg.OtpHash,
		arg.ExpiresAt,
		arg.Attempts,
		arg.VerifiedAt,
		arg.CreatedAt,
	)
	return err
}

const authCreatePhoneChangeChallenge = `-- name: AuthCreatePhoneChangeChallenge :exec
INSERT INTO phone_change_challenges (
    id, user_id, new_phone, otp_hash, expires_at, attempts, resend_count, last_sent_at, verified_at, created_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type AuthCreatePhoneChangeChallengeParams struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	NewPhone    string             `json:"new_phone"`
	OtpHash     string             `json:"otp_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Attempts    int32              `json:"attempts"`
	ResendCount int32              `json:"resend_count"`
	LastSentAt  pgtype.Timestamptz `json:"last_sent_at"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AuthCreatePhoneChangeChallenge(ctx context.Context, arg AuthCreatePhoneChangeChallengeParams) error {
	_, err := q.db.Exec(ctx, authCreatePhoneChangeChallenge,
		arg.ID,
		arg.UserID,
		arg.NewPhone,
		arg.OtpHash,
		arg.ExpiresAt,
		arg.Attempts,
		arg.ResendCount,
		arg.LastSentAt,
		arg.VerifiedAt,
		arg.CreatedAt,
	)
	return err
}

const authDeleteUnverifiedPhoneChangeChallengesByUserID = `-- name: AuthDeleteUnverifiedPhoneChangeChallengesByUserID :exec
DELETE FROM phone_change_challenges
WHERE user_id = $1::uuid
  AND verified_at IS NULL
`

func (q *Queries) AuthDeleteUnverifiedPhoneChangeChallengesByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, authDeleteUnverifiedPhoneChangeChallengesByUserID, userID)
	return err
}

const authGetLoginChallengeByID = `-- name: AuthGetLoginChallengeByID :one
SELECT
    id::text AS id,
    user_id::text AS user_id,
    otp_hash,
    expires_at,
    attempts,
    verified_at,
    created_at
FROM login_challenges
WHERE id = $1::uuid
`

type AuthGetLoginChallengeByIDRow struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	OtpHash    string             `json:"otp_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AuthGetLoginChallengeByID(ctx context.Context, challengeID pgtype.UUID) (AuthGetLoginChallengeByIDRow, error) {
	row := q.db.QueryRow(ctx, authGetLoginChallengeByID, challengeID)
	var i AuthGetLoginChallengeByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const authGetPasswordHashByUserID = `-- name: AuthGetPasswordHashByUserID :one
SELECT c.password_hash
FROM user_credentials c
JOIN users u ON u.id = c.user_id
WHERE c.user_id = $1::uuid
  AND u.status = 'active'
`

func (q *Queries) AuthGetPasswordHashByUserID(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, authGetPasswordHashByUserID, userID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const authGetPhoneChangeChallengeByID = `-- name: AuthGetPhoneChangeChallengeByID :one
SELECT
    id::text AS id,
    user_id::text AS user_id,
    new_phone,
    otp_hash,
    expires_at,
    attempts,
    resend_count,
    last_sent_at,
    verified_at,
    created_at
FROM phone_change_challenges
WHERE id = $1::uuid
`

type AuthGetPhoneChangeChallengeByIDRow struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	NewPhone    string             `json:"new_phone"`
	OtpHash     string             `json:"otp_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Attempts    int32              `json:"attempts"`
	ResendCount int32              `json:"resend_count"`
	LastSentAt  pgtype.Timestamptz `json:"last_sent_at"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AuthGetPhoneChangeChallengeByID(ctx context.Context, challengeID pgtype.UUID) (AuthGetPhoneChangeChallengeByIDRow, error) {
	row := q.db.QueryRow(ctx, authGetPhoneChangeChallengeByID, challengeID)
	var i AuthGetPhoneChangeChallengeByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewPhone,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ResendCount,
		&i.LastSentAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const authGetTokenVersionByUserID = `-- name: AuthGetTokenVersionByUserID :one
SELECT token_version
FROM users
WHERE id = $1::uuid
  AND status = 'active'
`

func (q *Queries) AuthGetTokenVersionByUserID(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, authGetTokenVersionByUserID, userID)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const authGetUserByAccount = `-- name: AuthGetUserByAccount :one
SELECT
    u.id::text AS id,
    COALESCE(u.tenant_id::text, '') AS tenant_id,
    COALESCE(t.display_name, '') AS tenant_name,
    u.name,
    COALESCE(u.phone, '') AS phone,
    u.role,
    u.scope_type,
    u.token_version,
    COALESCE(u.must_change_password, false) AS must_change_password,
    u.password_updated_at,
    c.password_hash
FROM users u
JOIN user_credentials c ON c.user_id = u.id
LEFT JOIN tenants t ON t.id = u.tenant_id
WHERE c.account = $1
  AND u.status = 'active'
`

type AuthGetUserByAccountRow struct {
	ID                 string             `json:"id"`
	TenantID           interface{}        `json:"tenant_id"`
	TenantName         string             `json:"tenant_name"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	Role               string             `json:"role"`
	ScopeType          string             `json:"scope_type"`
	TokenVersion       int32              `json:"token_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordUpdatedAt  pgtype.Timestamptz `json:"password_updated_at"`
	PasswordHash       string             `json:"password_hash"`
}

func (q *Queries) AuthGetUserByAccount(ctx context.Context, account string) (AuthGetUserByAccountRow, error) {
	row := q.db.QueryRow(ctx, authGetUserByAccount, account)
	var i AuthGetUserByAccountRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TenantName,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.ScopeType,
		&i.TokenVersion,
		&i.MustChangePassword,
		&i.PasswordUpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const authGetUserByID = `-- name: AuthGetUserByID :one
SELECT
    u.id::text AS id,
    COALESCE(u.tenant_id::text, '') AS tenant_id,
    COALESCE(t.display_name, '') AS tenant_name,
    u.name,
    COALESCE(u.phone, '') AS phone,
    u.role,
    u.scope_type,
    u.token_version,
    COALESCE(u.must_change_password, false) AS must_change_password,
    u.password_updated_at
FROM users u
LEFT JOIN tenants t ON t.id = u.tenant_id
WHERE u.id = $1::uuid
  AND u.status = 'active'
`

type AuthGetUserByIDRow struct {
	ID                 string             `json:"id"`
	TenantID           interface{}        `json:"tenant_id"`
	TenantName         string             `json:"tenant_name"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	Role               string             `json:"role"`
	ScopeType          string             `json:"scope_type"`
	TokenVersion       int32              `json:"token_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordUpdatedAt  pgtype.Timestamptz `json:"password_updated_at"`
}

func (q *Queries) AuthGetUserByID(ctx context.Context, userID pgtype.UUID) (AuthGetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, authGetUserByID, userID)
	var i AuthGetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TenantName,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.ScopeType,
		&i.TokenVersion,
		&i.MustChangePassword,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const authIncreaseLoginChallengeAttempts = `-- name: AuthIncreaseLoginChallengeAttempts :exec
UPDATE login_challenges
SET attempts = attempts + 1
WHERE id = $1::uuid
`

func (q *Queries) AuthIncreaseLoginChallengeAttempts(ctx context.Context, challengeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, authIncreaseLoginChallengeAttempts, challengeID)
	return err
}

const authIncreasePhoneChangeChallengeAttempts = `-- name: AuthIncreasePhoneChangeChallengeAttempts :exec
UPDATE phone_change_challenges
SET attempts = attempts + 1
WHERE id = $1::uuid
`

func (q *Queries) AuthIncreasePhoneChangeChallengeAttempts(ctx context.Context, challengeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, authIncreasePhoneChangeChallengeAttempts, challengeID)
	return err
}

const authMarkLoginChallengeVerified = `-- name: AuthMarkLoginChallengeVerified :exec
UPDATE login_challenges
SET verified_at = now()
WHERE id = $1::uuid
  AND verified_at IS NULL
`

func (q *Queries) AuthMarkLoginChallengeVerified(ctx context.Context, challengeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, authMarkLoginChallengeVerified, challengeID)
	return err
}

const authMarkPhoneChangeChallengeVerified = `-- name: AuthMarkPhoneChangeChallengeVerified :exec
UPDATE phone_change_challenges
SET verified_at = now()
WHERE id = $1::uuid
  AND verified_at IS NULL
`

func (q *Queries) AuthMarkPhoneChangeChallengeVerified(ctx context.Context, challengeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, authMarkPhoneChangeChallengeVerified, challengeID)
	return err
}

const authPhoneExists = `-- name: AuthPhoneExists :one
SELECT EXISTS(
    SELECT 1 FROM users
    WHERE phone = $1
      AND status = 'active'
)
`

func (q *Queries) AuthPhoneExists(ctx context.Context, phone pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, authPhoneExists, phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const authUpdateDisplayNameByUserID = `-- name: AuthUpdateDisplayNameByUserID :exec
UPDATE users
SET name = $1
WHERE id = $2::uuid
  AND status = 'active'
`

type AuthUpdateDisplayNameByUserIDParams struct {
	Name   string      `json:"name"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AuthUpdateDisplayNameByUserID(ctx context.Context, arg AuthUpdateDisplayNameByUserIDParams) error {
	_, err := q.db.Exec(ctx, authUpdateDisplayNameByUserID, arg.Name, arg.UserID)
	return err
}

const authUpdatePasswordHashByUserID = `-- name: AuthUpdatePasswordHashByUserID :exec
UPDATE user_credentials
SET password_hash = $1
WHERE user_id = $2::uuid
`

type AuthUpdatePasswordHashByUserIDParams struct {
	PasswordHash string      `json:"password_hash"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) AuthUpdatePasswordHashByUserID(ctx context.Context, arg AuthUpdatePasswordHashByUserIDParams) error {
	_, err := q.db.Exec(ctx, authUpdatePasswordHashByUserID, arg.PasswordHash, arg.UserID)
	return err
}

const authUpdatePasswordMetaByUserID = `-- name: AuthUpdatePasswordMetaByUserID :exec
UPDATE users
SET must_change_password = $1,
    password_updated_at = now(),
    token_version = token_version + 1
WHERE id = $2::uuid
`

type AuthUpdatePasswordMetaByUserIDParams struct {
	MustChangePassword bool        `json:"must_change_password"`
	UserID             pgtype.UUID `json:"user_id"`
}

func (q *Queries) AuthUpdatePasswordMetaByUserID(ctx context.Context, arg AuthUpdatePasswordMetaByUserIDParams) error {
	_, err := q.db.Exec(ctx, authUpdatePasswordMetaByUserID, arg.MustChangePassword, arg.UserID)
	return err
}

const authUpdatePhoneByUserID = `-- name: AuthUpdatePhoneByUserID :exec
UPDATE users
SET phone = $1,
    token_version = token_version + 1
WHERE id = $2::uuid
`

type AuthUpdatePhoneByUserIDParams struct {
	Phone  pgtype.Text `json:"phone"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AuthUpdatePhoneByUserID(ctx context.Context, arg AuthUpdatePhoneByUserIDParams) error {
	_, err := q.db.Exec(ctx, authUpdatePhoneByUserID, arg.Phone, arg.UserID)
	return err
}
