// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlcpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fileCreate = `-- name: FileCreate :exec
INSERT INTO files (
    id, tenant_id, bucket, object_key, size, mime, owner_type, owner_id, created_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8::uuid,
    $9
)
`

type FileCreateParams struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Bucket    string             `json:"bucket"`
	ObjectKey string             `json:"object_key"`
	Size      int64              `json:"size"`
	Mime      string             `json:"mime"`
	OwnerType string             `json:"owner_type"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FileCreate(ctx context.Context, arg FileCreateParams) error {
	_, err := q.db.Exec(ctx, fileCreate,
		arg.ID,
		arg.TenantID,
		arg.Bucket,
		arg.ObjectKey,
		arg.Size,
		arg.Mime,
		arg.OwnerType,
		arg.OwnerID,
		arg.CreatedAt,
	)
	return err
}
