// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcpg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLogs struct {
	ID                  pgtype.UUID        `json:"id"`
	RequestID           string             `json:"request_id"`
	OperatorUserID      pgtype.UUID        `json:"operator_user_id"`
	OperatorRole        pgtype.Text        `json:"operator_role"`
	OperatorTenantID    pgtype.UUID        `json:"operator_tenant_id"`
	OperatorUsername    string             `json:"operator_username"`
	OperatorDisplayName string             `json:"operator_display_name"`
	TargetType          string             `json:"target_type"`
	TargetID            pgtype.Text        `json:"target_id"`
	TargetName          pgtype.Text        `json:"target_name"`
	Action              string             `json:"action"`
	Module              string             `json:"module"`
	Result              string             `json:"result"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	BeforeJson          []byte             `json:"before_json"`
	AfterJson           []byte             `json:"after_json"`
	ChangedFields       []byte             `json:"changed_fields"`
	Ip                  pgtype.Text        `json:"ip"`
	UserAgent           pgtype.Text        `json:"user_agent"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type FileUploadSessions struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	UploadedBy  pgtype.UUID        `json:"uploaded_by"`
	ScopeType   string             `json:"scope_type"`
	BizType     string             `json:"biz_type"`
	FileName    string             `json:"file_name"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	FileUrl     string             `json:"file_url"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
	MimeType    string             `json:"mime_type"`
	DurationSec int32              `json:"duration_sec"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	LastError   string             `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Files struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Bucket    string             `json:"bucket"`
	ObjectKey string             `json:"object_key"`
	Size      int64              `json:"size"`
	Mime      string             `json:"mime"`
	OwnerType string             `json:"owner_type"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LoginChallenges struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	OtpHash    string             `json:"otp_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PhoneChangeChallenges struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	NewPhone    string             `json:"new_phone"`
	OtpHash     string             `json:"otp_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Attempts    int32              `json:"attempts"`
	ResendCount int32              `json:"resend_count"`
	LastSentAt  pgtype.Timestamptz `json:"last_sent_at"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RbacPolicies struct {
	ID       int64       `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Ptype    string      `json:"ptype"`
	V0       pgtype.Text `json:"v0"`
	V1       pgtype.Text `json:"v1"`
	V2       pgtype.Text `json:"v2"`
	V3       pgtype.Text `json:"v3"`
	V4       pgtype.Text `json:"v4"`
	V5       pgtype.Text `json:"v5"`
}

type Tenants struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	RegionCode   pgtype.Text        `json:"region_code"`
	Disabled     bool               `json:"disabled"`
	DisplayName  string             `json:"display_name"`
	Province     pgtype.Text        `json:"province"`
	City         pgtype.Text        `json:"city"`
	District     pgtype.Text        `json:"district"`
	Address      pgtype.Text        `json:"address"`
	ContactName  pgtype.Text        `json:"contact_name"`
	ContactPhone pgtype.Text        `json:"contact_phone"`
	Remark       pgtype.Text        `json:"remark"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserCredentials struct {
	UserID       pgtype.UUID        `json:"user_id"`
	Account      string             `json:"account"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Users struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Name               string             `json:"name"`
	Phone              pgtype.Text        `json:"phone"`
	Role               string             `json:"role"`
	ScopeType          string             `json:"scope_type"`
	Status             string             `json:"status"`
	TokenVersion       int32              `json:"token_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordUpdatedAt  pgtype.Timestamptz `json:"password_updated_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
