// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant.sql

package sqlcpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenants = `-- name: CountTenants :one
SELECT COUNT(1)
FROM tenants t
WHERE ($1 = '' OR t.display_name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR COALESCE(t.province, '') = $2)
  AND ($3 = '' OR COALESCE(t.city, '') = $3)
  AND ($4 = '' OR COALESCE(t.district, '') = $4)
  AND ($5 = '' OR t.status = $5)
`

type CountTenantsParams struct {
	Keyword  interface{} `json:"keyword"`
	Province interface{} `json:"province"`
	City     interface{} `json:"city"`
	District interface{} `json:"district"`
	Status   interface{} `json:"status"`
}

func (q *Queries) CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants,
		arg.Keyword,
		arg.Province,
		arg.City,
		arg.District,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (
    id, name, display_name, province, city, district, address,
    contact_name, contact_phone, remark, status, created_at, updated_at
)
VALUES (
    $1,
    $2,
    $2,
    NULLIF($3, ''),
    NULLIF($4, ''),
    NULLIF($5, ''),
    NULLIF($6, ''),
    NULLIF($7, ''),
    NULLIF($8, ''),
    NULLIF($9, ''),
    $10,
    $11,
    $12
)
`

type CreateTenantParams struct {
	ID           pgtype.UUID        `json:"id"`
	DisplayName  string             `json:"display_name"`
	Province     interface{}        `json:"province"`
	City         interface{}        `json:"city"`
	District     interface{}        `json:"district"`
	Address      interface{}        `json:"address"`
	ContactName  interface{}        `json:"contact_name"`
	ContactPhone interface{}        `json:"contact_phone"`
	Remark       interface{}        `json:"remark"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant,
		arg.ID,
		arg.DisplayName,
		arg.Province,
		arg.City,
		arg.District,
		arg.Address,
		arg.ContactName,
		arg.ContactPhone,
		arg.Remark,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createTenantAdminCredential = `-- name: CreateTenantAdminCredential :exec
INSERT INTO user_credentials (user_id, account, password_hash, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateTenantAdminCredentialParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	Account      string             `json:"account"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTenantAdminCredential(ctx context.Context, arg CreateTenantAdminCredentialParams) error {
	_, err := q.db.Exec(ctx, createTenantAdminCredential,
		arg.UserID,
		arg.Account,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const createTenantAdminUser = `-- name: CreateTenantAdminUser :exec
INSERT INTO users (id, tenant_id, name, phone, role, scope_type, status, created_at, must_change_password)
VALUES (
    $1,
    $2,
    $3,
    NULLIF($4, ''),
    'tenant_admin',
    'tenant',
    $5,
    $6,
    true
)
`

type CreateTenantAdminUserParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Phone     interface{}        `json:"phone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTenantAdminUser(ctx context.Context, arg CreateTenantAdminUserParams) error {
	_, err := q.db.Exec(ctx, createTenantAdminUser,
		arg.UserID,
		arg.TenantID,
		arg.Name,
		arg.Phone,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const displayNameExists = `-- name: DisplayNameExists :one
SELECT EXISTS(SELECT 1 FROM tenants WHERE display_name = $1)
`

func (q *Queries) DisplayNameExists(ctx context.Context, displayName string) (bool, error) {
	row := q.db.QueryRow(ctx, displayNameExists, displayName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTenantAdminByTenantID = `-- name: GetTenantAdminByTenantID :one
SELECT
    u.id::text AS user_id,
    COALESCE(u.tenant_id::text, '') AS tenant_id,
    u.name,
    COALESCE(u.phone, '') AS phone,
    u.role,
    u.scope_type,
    u.token_version,
    COALESCE(u.must_change_password, false) AS must_change_password,
    u.password_updated_at,
    c.account
FROM users u
JOIN user_credentials c ON c.user_id = u.id
WHERE u.tenant_id = $1
  AND u.role = 'tenant_admin'
  AND u.status = 'active'
ORDER BY u.created_at ASC, u.id ASC
LIMIT 1
`

type GetTenantAdminByTenantIDRow struct {
	UserID             string             `json:"user_id"`
	TenantID           interface{}        `json:"tenant_id"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	Role               string             `json:"role"`
	ScopeType          string             `json:"scope_type"`
	TokenVersion       int32              `json:"token_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordUpdatedAt  pgtype.Timestamptz `json:"password_updated_at"`
	Account            string             `json:"account"`
}

func (q *Queries) GetTenantAdminByTenantID(ctx context.Context, tenantID pgtype.UUID) (GetTenantAdminByTenantIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantAdminByTenantID, tenantID)
	var i GetTenantAdminByTenantIDRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.ScopeType,
		&i.TokenVersion,
		&i.MustChangePassword,
		&i.PasswordUpdatedAt,
		&i.Account,
	)
	return i, err
}

const getTenantAdminByUserID = `-- name: GetTenantAdminByUserID :one
SELECT
    u.id::text AS user_id,
    COALESCE(u.tenant_id::text, '') AS tenant_id,
    u.name,
    COALESCE(u.phone, '') AS phone,
    u.role,
    u.scope_type,
    u.token_version,
    COALESCE(u.must_change_password, false) AS must_change_password,
    u.password_updated_at,
    c.account
FROM users u
JOIN user_credentials c ON c.user_id = u.id
WHERE u.id = $1
  AND u.role = 'tenant_admin'
  AND u.status = 'active'
LIMIT 1
`

type GetTenantAdminByUserIDRow struct {
	UserID             string             `json:"user_id"`
	TenantID           interface{}        `json:"tenant_id"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	Role               string             `json:"role"`
	ScopeType          string             `json:"scope_type"`
	TokenVersion       int32              `json:"token_version"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordUpdatedAt  pgtype.Timestamptz `json:"password_updated_at"`
	Account            string             `json:"account"`
}

func (q *Queries) GetTenantAdminByUserID(ctx context.Context, userID pgtype.UUID) (GetTenantAdminByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantAdminByUserID, userID)
	var i GetTenantAdminByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.ScopeType,
		&i.TokenVersion,
		&i.MustChangePassword,
		&i.PasswordUpdatedAt,
		&i.Account,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT
    id::text AS tenant_id,
    display_name,
    COALESCE(province, '') AS province,
    COALESCE(city, '') AS city,
    COALESCE(district, '') AS district,
    COALESCE(address, '') AS address,
    COALESCE(contact_name, '') AS contact_name,
    COALESCE(contact_phone, '') AS contact_phone,
    COALESCE(remark, '') AS remark,
    status,
    created_at,
    updated_at
FROM tenants
WHERE id = $1
`

type GetTenantByIDRow struct {
	TenantID     string             `json:"tenant_id"`
	DisplayName  string             `json:"display_name"`
	Province     string             `json:"province"`
	City         string             `json:"city"`
	District     string             `json:"district"`
	Address      string             `json:"address"`
	ContactName  string             `json:"contact_name"`
	ContactPhone string             `json:"contact_phone"`
	Remark       string             `json:"remark"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTenantByID(ctx context.Context, tenantID pgtype.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantID)
	var i GetTenantByIDRow
	err := row.Scan(
		&i.TenantID,
		&i.DisplayName,
		&i.Province,
		&i.City,
		&i.District,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasTenantAdmin = `-- name: HasTenantAdmin :one
SELECT EXISTS (
    SELECT 1
    FROM users u
    JOIN user_credentials c ON c.user_id = u.id
    WHERE u.tenant_id = $1
      AND u.role = 'tenant_admin'
)
`

func (q *Queries) HasTenantAdmin(ctx context.Context, tenantID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasTenantAdmin, tenantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTenantsPage = `-- name: ListTenantsPage :many
SELECT
    t.id::text AS tenant_id,
    t.display_name,
    COALESCE(t.province, '') AS province,
    COALESCE(t.city, '') AS city,
    COALESCE(t.district, '') AS district,
    COALESCE(t.address, '') AS address,
    COALESCE(t.contact_name, '') AS contact_name,
    COALESCE(t.contact_phone, '') AS contact_phone,
    COALESCE(t.remark, '') AS remark,
    t.status,
    t.created_at,
    t.updated_at,
    COALESCE(ta.user_id::text, '') AS tenant_admin_user_id,
    COALESCE(ta.account, '') AS tenant_admin_account,
    COALESCE(ta.name, '') AS tenant_admin_name,
    COALESCE(ta.phone, '') AS tenant_admin_phone
FROM tenants t
LEFT JOIN LATERAL (
    SELECT u.id AS user_id, c.account, u.name, u.phone
    FROM users u
    LEFT JOIN user_credentials c ON c.user_id = u.id
    WHERE u.tenant_id = t.id AND u.role = 'tenant_admin'
    ORDER BY u.created_at ASC, u.id ASC
    LIMIT 1
) ta ON true
WHERE ($1 = '' OR t.display_name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR COALESCE(t.province, '') = $2)
  AND ($3 = '' OR COALESCE(t.city, '') = $3)
  AND ($4 = '' OR COALESCE(t.district, '') = $4)
  AND ($5 = '' OR t.status = $5)
ORDER BY t.created_at DESC, t.id DESC
LIMIT $7 OFFSET $6
`

type ListTenantsPageParams struct {
	Keyword    interface{} `json:"keyword"`
	Province   interface{} `json:"province"`
	City       interface{} `json:"city"`
	District   interface{} `json:"district"`
	Status     interface{} `json:"status"`
	OffsetRows int32       `json:"offset_rows"`
	LimitRows  int32       `json:"limit_rows"`
}

type ListTenantsPageRow struct {
	TenantID           string             `json:"tenant_id"`
	DisplayName        string             `json:"display_name"`
	Province           string             `json:"province"`
	City               string             `json:"city"`
	District           string             `json:"district"`
	Address            string             `json:"address"`
	ContactName        string             `json:"contact_name"`
	ContactPhone       string             `json:"contact_phone"`
	Remark             string             `json:"remark"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TenantAdminUserID  interface{}        `json:"tenant_admin_user_id"`
	TenantAdminAccount string             `json:"tenant_admin_account"`
	TenantAdminName    string             `json:"tenant_admin_name"`
	TenantAdminPhone   string             `json:"tenant_admin_phone"`
}

func (q *Queries) ListTenantsPage(ctx context.Context, arg ListTenantsPageParams) ([]ListTenantsPageRow, error) {
	rows, err := q.db.Query(ctx, listTenantsPage,
		arg.Keyword,
		arg.Province,
		arg.City,
		arg.District,
		arg.Status,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantsPageRow
	for rows.Next() {
		var i ListTenantsPageRow
		if err := rows.Scan(
			&i.TenantID,
			&i.DisplayName,
			&i.Province,
			&i.City,
			&i.District,
			&i.Address,
			&i.ContactName,
			&i.ContactPhone,
			&i.Remark,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantAdminUserID,
			&i.TenantAdminAccount,
			&i.TenantAdminName,
			&i.TenantAdminPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTenantAdminPasswordReset = `-- name: MarkTenantAdminPasswordReset :exec
UPDATE users
SET must_change_password = true,
    password_updated_at = now(),
    token_version = token_version + 1
WHERE id = $1
`

func (q *Queries) MarkTenantAdminPasswordReset(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markTenantAdminPasswordReset, userID)
	return err
}

const tenantAdminAccountExists = `-- name: TenantAdminAccountExists :one
SELECT EXISTS(SELECT 1 FROM user_credentials WHERE account = $1)
`

func (q *Queries) TenantAdminAccountExists(ctx context.Context, account string) (bool, error) {
	row := q.db.QueryRow(ctx, tenantAdminAccountExists, account)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tenantAdminPhoneExists = `-- name: TenantAdminPhoneExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE phone = $1)
`

func (q *Queries) TenantAdminPhoneExists(ctx context.Context, phone pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, tenantAdminPhoneExists, phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const toggleTenantStatus = `-- name: ToggleTenantStatus :execrows
UPDATE tenants
SET status = $1, updated_at = now()
WHERE id = $2
`

type ToggleTenantStatusParams struct {
	Status   string      `json:"status"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ToggleTenantStatus(ctx context.Context, arg ToggleTenantStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, toggleTenantStatus, arg.Status, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTenant = `-- name: UpdateTenant :execrows
UPDATE tenants
SET name = $1,
    display_name = $1,
    province = NULLIF($2, ''),
    city = NULLIF($3, ''),
    district = NULLIF($4, ''),
    address = NULLIF($5, ''),
    contact_name = NULLIF($6, ''),
    contact_phone = NULLIF($7, ''),
    remark = NULLIF($8, ''),
    updated_at = $9
WHERE id = $10
`

type UpdateTenantParams struct {
	DisplayName  string             `json:"display_name"`
	Province     interface{}        `json:"province"`
	City         interface{}        `json:"city"`
	District     interface{}        `json:"district"`
	Address      interface{}        `json:"address"`
	ContactName  interface{}        `json:"contact_name"`
	ContactPhone interface{}        `json:"contact_phone"`
	Remark       interface{}        `json:"remark"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTenant,
		arg.DisplayName,
		arg.Province,
		arg.City,
		arg.District,
		arg.Address,
		arg.ContactName,
		arg.ContactPhone,
		arg.Remark,
		arg.UpdatedAt,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTenantAdminAccount = `-- name: UpdateTenantAdminAccount :exec
UPDATE user_credentials
SET account = $1
WHERE user_id = $2
`

type UpdateTenantAdminAccountParams struct {
	Account string      `json:"account"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateTenantAdminAccount(ctx context.Context, arg UpdateTenantAdminAccountParams) error {
	_, err := q.db.Exec(ctx, updateTenantAdminAccount, arg.Account, arg.UserID)
	return err
}

const updateTenantAdminPassword = `-- name: UpdateTenantAdminPassword :exec
UPDATE user_credentials
SET password_hash = $1
WHERE user_id = $2
`

type UpdateTenantAdminPasswordParams struct {
	PasswordHash string      `json:"password_hash"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateTenantAdminPassword(ctx context.Context, arg UpdateTenantAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateTenantAdminPassword, arg.PasswordHash, arg.UserID)
	return err
}

const updateTenantAdminProfile = `-- name: UpdateTenantAdminProfile :exec
UPDATE users
SET name = $1,
    phone = NULLIF($2, '')
WHERE id = $3
`

type UpdateTenantAdminProfileParams struct {
	Name   string      `json:"name"`
	Phone  interface{} `json:"phone"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateTenantAdminProfile(ctx context.Context, arg UpdateTenantAdminProfileParams) error {
	_, err := q.db.Exec(ctx, updateTenantAdminProfile, arg.Name, arg.Phone, arg.UserID)
	return err
}

const updateUsersStatusByTenantID = `-- name: UpdateUsersStatusByTenantID :exec
UPDATE users
SET status = $1
WHERE tenant_id = $2
`

type UpdateUsersStatusByTenantIDParams struct {
	Status   string      `json:"status"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateUsersStatusByTenantID(ctx context.Context, arg UpdateUsersStatusByTenantIDParams) error {
	_, err := q.db.Exec(ctx, updateUsersStatusByTenantID, arg.Status, arg.TenantID)
	return err
}
